### ISSUE TITLE
reduce minSdkVersion

### ISSUE THREAD

**Issue by alexodus** [borjabravo10/ReadMoreTextView#2]
Please, reduce minSdkVersion to 15 (now is 16)

**Comment by borjabravo10** [comment]
Hi @alexodus. I have decided not to include the API 15, because it only has a 2.2% coverage: http://developer.android.com/intl/es/about/dashboards/index.html
Is it absolutely necessary for you to use it in a project? If so, I can check it for the next release. No problem, thanks and best regards

**Comment by alexodus** [comment]
Hi, I need it for my app

**Comment by yolapop** [comment]
@borjabravo10 Any reason why you can't reduce SDK other than small coverage? Can you just reduce it until gingerbread?

**Comment by borjabravo10** [comment]
@yolapop @alexodus No problem. Tomorrow I'll upload a new release with some bugs fixed and I'll reduce the minSdkVersion until gingerbread

**Comment by yolapop** [comment]
Thanks @borjabravo10 👍🏻

**Comment by borjabravo10** [comment]
@alexodus @yolapop updated --> v1.1.2
