### ISSUE TITLE
[FEATURE] trim for lines

### ISSUE THREAD

**Issue by alexodus** [borjabravo10/ReadMoreTextView#3]
allow to have a trim lines based not only lenght based

**Comment by borjabravo10** [comment]
In the next release, I will add this feature

**Comment by borjabravo10** [comment]
@alexodus I'm in development of this feature. In two or three days, the new release will uploaded

**Comment by LiuJQ** [comment]
@alexodus Have you achieved this function ?

**Comment by borjabravo10** [comment]
@LiuJQ No, in this moment, only it can trim with length

**Comment by LiuJQ** [comment]
I have tried, and there is my codes:
`/**
     * register a listener to refresh the lineEndIndex for TRIM_MODE_LINE
     */
    private void registerListener2refreshLineEndIndex() {
        getViewTreeObserver().addOnGlobalLayoutListener(new ViewTreeObserver.OnGlobalLayoutListener() {
            @Override
            public void onGlobalLayout() {
                if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.JELLY_BEAN) {
                    ViewTreeObserver obs = getViewTreeObserver();
                    obs.removeOnGlobalLayoutListener(this);
                }
                if (trimMode == TRIM_MODE_LINE) {
                    // only try to get the lineEndIndex in TRIM_MODE_LINE mode
                    refreshLineEndIndex();
                }
            }
        });
    }

    /**
     * refresh lineEndIndex
     */
    private void refreshLineEndIndex() {
        try {
            int height = getHeight();
            int scrollY = getScrollY();
            Layout layout = getLayout();
            if (layout != null) {
                int lastVisibleLineNumber = layout.getLineForVertical(scrollY + height);
                if (trimLines < lastVisibleLineNumber) {
                    lineEndIndex = layout.getLineEnd(trimLines - 1);
                } else {
                    lineEndIndex = layout.getLineEnd(lastVisibleLineNumber - 1);
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }`
let trimEndIndex equals to EndIndex of the specify trimLine:
`private CharSequence updateCollapsedText() {
        int trimEndIndex = text.length();
        switch (trimMode) {
            case TRIM_MODE_LINE:
                Log.d(TAG, "lineEndIndex = " + lineEndIndex);
                trimEndIndex = lineEndIndex - (ELLIPSIZE.length() + trimCollapsedText.length() + 1);
                if (trimEndIndex < 0) {
                    trimEndIndex = trimLength + 1;
                }
                break;
            case TRIM_MODE_LENGTH:
                trimEndIndex = trimLength + 1;
                break;
        }
        SpannableStringBuilder s = new SpannableStringBuilder(text, 0, trimEndIndex)
                .append(ELLIPSIZE)
                .append(trimCollapsedText);
        return addClickableSpan(s, trimCollapsedText);
    }`

this can be useful, **BUT** there is a bug that text will be trim at start for the first time initialized, so sad.

**Comment by borjabravo10** [comment]
@LiuJQ I'll review this code, thanks

**Comment by LiuJQ** [comment]
Hey @borjabravo10 , thanks for attention. I try to make thing perfect but I failed.
As mentioned above, there is a **BUG** that text will be trim at start for the first time initialized, everything looks right **only** when 'expand'(clickablespan) is clicked by user.

So I revert my changes.

**Comment by borjabravo10** [comment]
Hi @LiuJQ , I'll review your changes and I'll try to get it to work the first time. It´s a problem with onGlobalLayout native implementation. When I get this feature, I'll upload a new release

**Comment by LiuJQ** [comment]
Hi @borjabravo10 , that's pretty good ! I couldn't wait any more to see your release. :)

**Comment by borjabravo10** [comment]
@alexodus @LiuJQ new release has been uploaded with this feature :)

**Comment by LiuJQ** [comment]
Wow, amazing ! Nice job :)
But I think there's a little mistake:
```java
this.trimMode = typedArray.getInt(R.styleable.ReadMoreTextView_trimLines, TRIM_MODE_LINES);
```
should be:
```java
this.trimMode = typedArray.getInt(R.styleable.ReadMoreTextView_trimMode, TRIM_MODE_LINES);
```

**Comment by borjabravo10** [comment]
you're right, I've changed this mistake ;)
