### ISSUE TITLE
BUG

### ISSUE THREAD

**Issue by DuShuYuan** [borjabravo10/ReadMoreTextView#8]
tv.setText(str);   //无效

修复：
ReadMoreTextView.java

    @Override
    public void setText(CharSequence text, BufferType type) {
        this.text = text;
        bufferType = type;
        **onGlobalLayoutLineEndIndex();**
        setText();
    }

**Comment by borjabravo10** [comment]
Can you tell me what is the mistake? In english please...
I don't understand your comments in chinese, sorry.

**Comment by eVerup** [comment]
It solve my problem of settext with delay (after oncreate).
Thanks so much @DuShuYuan  !
